### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by JiHaoqina** [Ir1d/DARKFACE_eval_tools#13]
Hi,
When I use the recommended command 'docker run --rm -it ....', I had some questions.

'''
 the second one is the folder which contains ground_truth
 the third one is the folder which contains your submission
'''

1. is the gt folder(./data/gt) in the docker images? But it shows 'Can not find the gt file ./data/gt/1.txt' when I run the command.
2. About my prediction file. I don't have a complete set of tests (only 100), and I don't know what the prediction file should be.

Plz help me, Thanks!

**Comment by Ir1d** [comment]
1. `./data/gt` should be the path in the docker image. it cant find the gt file because the gt file is not inside the docker image, you have to bind the `./data/gt` to the correct folder.
2. the format of the prediction files can be found on the contest website, each line needs five numbers (four coordinates and a confidence).

**Comment by JiHaoqina** [comment]
@Ir1d but how can i get the complete test datasets and the corresponding gt file(4000 each)？

**Comment by Ir1d** [comment]
@JiHaoqina I'm not allowed to release the test datasets at this moment, I'll let you know when the test datasets are out.

**Comment by JiHaoqina** [comment]
@Ir1d Hi, Is this repo only for evaling test_sample(100 images)? How can I eval on the whole testing set of DarkFace(4000 images)?
